/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        white: '#FFFFFF',
        'main-bg': '#0E0E0E',
        'main-sections': '#1A1919',
        'main-sections-2': '#242323',
        'surface-deep': '#121111',
        'main-menu-bg': '#1A1919',
        'main-overlay': '#4140424D',
        'main-accent-purple': '#612BD3',
        'main-accent-pink': '#FC69FF',
        'main-accent-blue': '#618DFF',
        'background-primary': '#1A1919',
        'icon-primary': '#A3A3A3',
        'icon-secondary': '#656464',
        'icon-active': '#FFFFFF',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A3A3A3',
        'text-tertiary': '#454444',
        'text-critical': '#FF3F3F',
        'text-success': '#00EB75',
        'input-bg': '#1A1919',
        'input-stroke-default': '#2C2B2B',
        'input-stroke-active': '#8A62FD',
        'dropdown-bg-default': '#1A1919',
        'dropdown-stroke-default': '#2C2B2B',
        'dropdown-stroke-active': '#612BD3',
        'separator-primary': '#252525',
        'separator-scroll': '#2C2B2B',
        'slot-bg-default': '#1A1919',
        'slot-bg-header': '#3B64F6',
        'slot-bg-post': '#2C2B2B',
        'slot-stroke-default': '#232222',
        'slot-stroke-active': '#612BD3',
        'slot-day-bg': '#212020',
        'channel-active-bg': '#232222',
        'buttons-primary-bg': '#612BD3',
        'buttons-primary-text': '#FFFFFF',
        'buttons-secondary-bg': '#D82D7E',
        'buttons-secondary-text': '#FFFFFF',
        'buttons-tertiary-bg': '#313030',
        'buttons-tertiary-text': '#FFFFFF',
        'buttons-disabled-bg': '#3C3C3C',
        'buttons-disabled-text': '#9E9E9E',
        'buttons-menu-bg-active': '#FFFFFF',
        'buttons-menu-icon-active': '#0E0E0E',
        'buttons-menu-icons-default': '#A3A3A3',
        'buttons-stroke-text': '#FFFFFF',
        'buttons-stroke-stroke': '#FFFFFF14',
        'tab-text-default': '#A3A3A3',
        'tab-text-active': '#1A1919',
        'tab-bg-active': '#FFFFFF',
        'tab-bg-default': '#1A1919',
        'tab-stroke-default': '#2C2B2B',
        'tab-default-icon': '#A3A3A3',
        'google-black': '#0E0E0E',
        'google-green': '#34A853',
        'google-blue': '#4285F4',
        'google-blue-light': '#5383FF',
        'google-yellow': '#FBBC04',
        'google-red': '#EA4335',
      },
      fontFamily: {
        jakarta: ['PlusJakartaSans'],
        'jakarta-italic': ['PlusJakartaSans-Italic'],
      },
      fontSize: {
        h1: ['24px', { lineHeight: '34px' }],
        h2: ['20px', { lineHeight: '28px' }],
        h3: ['18px', { lineHeight: '26px' }],
        h4: ['15px', { lineHeight: '22px' }],
        button: ['15px', { lineHeight: '22px' }],
        'button-2': ['13px', { lineHeight: '18px' }],
        'body-1': ['14px', { lineHeight: '20px' }],
        'body-2': ['14px', { lineHeight: '20px' }],
        'body-3': ['13px', { lineHeight: '18px' }],
        'body-4': ['12px', { lineHeight: '17px' }],
        caption: ['10px', { lineHeight: '15px' }],
      },
    },
  },
  plugins: [],
};
